[package]
name = "hyshot-editor"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
sctk = { package = "smithay-client-toolkit", version = "0.21.1", default-features = false, features = [
    "calloop",
    "xkbcommon"
] }
wayland-client = {version = "0.31.11", features = ["log"]}
wayland-backend = { version = "0.3", features = ["client_system"] }
wayland-sys = "0.31"
wayland-protocols = {version = "0.32.9", features = ["client"]}
log = "0.4.29"
image = "0.25.9"
anyhow = "1.0.100"
notify-rust = "4.11"
wgpu = {version = "29"}
pollster = "1.0.1"
egui-wgpu = { version = "0.35.0", features = ["wayland"] }
egui = "0.35.0"
raw-window-handle = "0.6.2"
rustc-hash = "2.1.1"
egui_extras = {version = "0.35.0", features = ["svg"]}
indexmap = "2.13.0"
imageproc = "0.27.0"
spire_enum = "1.0.0"
delegate = "0.13.5"
taffy = "0.12.2"
smithay-clipboard = {git = "https://github.com/FengZhongShaoNian/smithay-clipboard.git", branch = "mime-types"}
rfd = "0.17.2"

[dev-dependencies]
tempfile = "3.10"
